name: max_lines

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  analyzer:
  custom_lint_builder:
    git:
      url: https://github.com/leggenda47/dart_custom_lint.git
      ref: main
      path: packages/custom_lint_builder

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
